version: '3'
services:
  #######################################
  # MySQL server
  #######################################
  alquran-db:
    build:
      context: .
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: quran
      MYSQL_PASSWORD: quran
      MYSQL_DATABASE: quran
      MYSQL_ROOT_PASSWORD: "root"
    ports:
    - "3306:3306"
    container_name: quran-db
